name: GameFramework
version: 0.2.7
author: SubSide
main: subside.frameworks.gameframework.GameFramework
description: GameFramework for various games

commands:
  gf:
    description: Game framework main command